name: Upload Python Package to PyPI and nodejs bindings to npm

on:
  release:
    types: [ published ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Version to Release Tag
        run: |
          # Extract the release tag number
          TAG=$(echo "${{ github.event.release.tag_name }}" | sed -E 's/v([0-9]+\.[0-9]+\.[0-9]+)/\1/')

          # Update the version file (version.py)
          sed -i "s/__version__ = \".*\"/__version__ = \"$TAG\"/" src/hvps/version.py

          # Update the package.json file
          sed -i "s/\"version\": \".*\",/\"version\": \"$TAG\",/" bindings/nodejs/package.json

          # Commit and push changes
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add src/hvps/version.py bindings/nodejs/package.json
          git commit -m "Update version to $TAG"
          git push

  build:
    runs-on: ubuntu-latest
    needs: [ update-version ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package 📦
        run: python -m build

      - name: Install package 📦
        run: python -m pip install .

      - name: Verify python package version matches tag
        run: |
          python -c "import hvps; assert '${{ github.event.release.tag_name }}' == 'v' + hvps.__version__"

      - name: Verify npm package version matches tag
        run: |
          python -c "import os,json;version=json.load(open('bindings/nodejs/package.json'))['version'];assert '${{ github.event.release.tag_name }}' == 'v' + version"

      - name: Cache dist directory
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}-${{ github.run_id}}-${{ github.run_number }}

  publish-to-pypi-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore dist from cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}-${{ github.run_id}}-${{ github.run_number }}

      - name: Publish package 📦 to TEST PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    needs: [ build, publish-to-pypi-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Restore dist from cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}-${{ github.run_id}}-${{ github.run_number }}

      - name: Publish package 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish-to-npm:
    needs: [ publish-to-pypi ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/nodejs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: bindings/nodejs/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
